#!/bin/bash

set -u

HERE="$(realpath "$(dirname "$0")")"

usage() {
    cat <<_END_
Usage: $0

This script install The Venusian onto your computer, or a file system e.g. of a Raspberry Pi.

  User:
    --user NAME
        The user for Venusian. The default is "venus".

        If you use this option without "--install",
        a new user for your existing Venus installation will be created.

    --ext ADDR/NET
        Use this IP adress on subnet NET for the container. "dyn" uses DHCP.
        e.g. --ext=192.168.1.2/24 or --ext=dyn

    --fb
        Use the system's "real" video output.

  System:
    --install, -I
        Install the venusian system.

        This option is the default if "--user" is not used.

    --image IMG|URL
        Install this image to "/opt/venus" (or DEST).

        The image can be a URL. The special value "-web-" downloads the current image,
        "-rc-" uses the latest release candidate.

        If this option is not used, "opt/venus" (or DEST) must contain an unpacked
        Venus root file system.

    --dest DIR
        Install the image to this directory.

        The default is "ROOT/opt/venus". A bind-mount will be created if a
        different destination is used.

    --root DIR
        Use this option to install The Venusian onto a mounted Linux file system.

    --verbose
        Print the steps the script executes.

    --quiet
        Do not report (coarse) progress.

    --skip
        Skip existing files.

    --replace
        Delete the existing Venusian installation before unpacking the new image.

    --no-update
        Don't update our git submodules. (Useful while developing.)

    --sub=ADDON
        Process add-on scripts. May be used more than once.

    --repo SOURCE
        Use this URL to fetch a sources.list file for additional Debian packages.
        Use "--repo -" to disable.
        The result will be stored in /etc/apt/sources.list.d/venusian.list

    --repo-key PUBKEYFILE
        Use this URL to fetch the GPG signature file associated with REPO.

  Available additions:
_END_
    ls -1 "$HERE/install.d" | while read d ; do echo -n "      $d  ";
        READ="$HERE/install.d/$d/README"
        if test -f "$READ" ; then head -1 "$READ"; else echo "‹no README file›"; fi
    done

    if [ "$(id -u)" != 0 ] ; then
        cat <<_END_

NB: This script needs to run as root.
_END_
    fi
    exit 1
}

apti() {
   R="$1"
   shift
   $Q echo Installing $@
   if test "$R" = "/" ; then
      apt-get install --yes --no-install-recommends -o Dpkg::Options::="--force-confdef" "$@" </dev/tty >/dev/tty 2>&1
   else
      systemd-nspawn -D "$R" apt-get install --yes --no-install-recommends -o Dpkg::Options::="--force-confdef" "$@" </dev/tty >/dev/tty 2>&1
   fi
}

packages() {
I=""
PI=""
DEBARCH="$(chr dpkg --print-architecture)"
case "$DEBARCH" in
    (armhf)
        # nothing to do
        ;;
    (*)
        PAGESIZE=$(getconf PAGE_SIZE)
        if [ "$DEBARCH" = "arm64" ] && [ "$PAGESIZE" -eq 4096 ]; then
            # 64-bit arm host with 4 KB pages → native armhf should work
            # if CONFIG_COMPAT=y is set in the kernel
            :
        else
            test -s "$R/usr/bin/qemu-arm" || I="$I qemu-user"
            test -s "$R/usr/share/binfmts/qemu-arm" || test -s "$R/usr/lib/binfmt.d/qemu-arm.conf" || I="$I qemu-user-binfmt"
        fi
        ;;
esac

test -s "$R/usr/bin/pstree" || I="$I psmisc"
test -s "$R/usr/bin/sudo" || I="$I sudo"
test -s "$R/usr/bin/make" || I="$I make"
test -s "$R/usr/sbin/iptables" || I="$I iptables"
test -s "$R/usr/bin/jq" || I="$I jq"
test -s "$R/usr/bin/nc.openbsd" || I="$I netcat-openbsd"
test -s "$R/usr/bin/socat" || I="$I socat"
test -s "$R/usr/bin/bluetoothctl" || I="$I bluez"
test -s "$R/usr/bin/fuse-overlayfs" || I="$I fuse-overlayfs"
test -s "$R/usr/sbin/nginx" || I="$I nginx"
test -s "$R/usr/share/doc/php-fpm" || I="$I php-fpm"
test -d "$R/usr/lib/python3/dist-packages/dbus_next" || I="$I python3-dbus-next"
test -d "$R/usr/lib/python3/dist-packages/dbus_fast" || I="$I python3-dbus-fast"
test -d "$R/usr/lib/python3/dist-packages/paho/mqtt" || I="$I python3-paho-mqtt"
test -d "$R/usr/lib/python3/dist-packages/serial_asyncio" || I="$I python3-serial-asyncio"

for P in anyio asyncdbus lxml dbus pyudev pymodbus dnslib websockets click asyncclick asyncdbus yaml attr outcome trio ; do
    test -d "$R/usr/lib/python3/dist-packages/$P" && continue
    if apt-cache show "python3-$P" >/dev/null 2>&1; then
        I="$I python3-$P"
    else
        PI="$PI $P"
    fi
done
test -z "$PI" || test -s "$R/usr/bin/pip3" || I="$I python3-pip"
subs pkg-r
test -z "$I" || apti "$R" $I
test -z "$PI" || pip3 install --no-cache-dir --break-system-packages $PI
}

subs() {
    W="$1"
    for S in "${SUB[@]}" ; do
        if test -f "$HERE/install.d/$S/$W" ; then
            $Q echo Processing "$S/$W"
            source "$HERE/install.d/$S/$W"
        fi
    done
}

_chg() {
    # check: do we replace DST from SRC?
    SRC="$1"
    DST="$2"
    test -n "$FORCE" && return 0
    test -f "$DST" || return 0
    test "$SRC" -ef "$DST" && return 0
    test "$SRC" -nt "$DST" && return 0
    cmp -s "$SRC" "$DST" && return 0
    # "cmp -s" compares sizes before reading, so we don't need to
    return 1
}

fcat() {
    # check: do we not replace DST?
    DST="$1" ; shift
    if [ -z "$FORCE" ] && [ -f "$DST" ] ; then cat >/dev/null ; return ; fi
    S1=0000
    if [ $# -gt 0 ] && [ -f "$DST" ] ; then
        S1=$(sha256sum < "$DST" | sed -e 's/ .*//')
    fi

    cat >"$DST"
    if [ $# -gt 0 ] && [ $S1 != $(sha256sum < "$DST" | sed -e 's/ .*//') ] ; then
        "$@"
    fi
}

fchg() {
    # check: do we not replace DST from SRC?
    SRC="$1"
    DST="$2"
    _chg "$SRC" "$DST" || return 0
    rm -f "$DST"
    mkdir -p "$(dirname "$DST")"
    touch "$DST"
    if test -x "$SRC" ; then chmod 755 "$DST"; else chmod 644 "$DST"; fi
    return 1
}

fln() {
    # To link or not to link …
    SRC="$1"
    DST="$2"
    if test -e "$DST" && ! test -L "$DST" ; then
        echo "ERROR: '$DST' is not a symlink. Exiting." >&2
        exit 1
    fi
    if test -z "$FORCE" && test -L "$DST" ; then return ; fi
    rm -f "$DST"
    ln -sf "$SRC" "$DST"
}


next_screen() {
    # well, "next" unless it's an existing user who already has a screen#
    if [ ! -d /etc/venusian ] ; then
        echo 1
        return 0
    fi
    local P=0 SC f NAME=$1
    while read f ; do
        SC="$(sed -ne 's/^SCREEN=//p' <$f)"
        if [ -n "$SC" ] && [ "$(basename "$(dirname "$f")")" = "$NAME" ] ; then
            echo $SC
            return 0
        fi
        test -z "$SC" || test "$SC" -le $P || P=$SC
    done < <( find "$R/etc/venusian" -maxdepth 2 -mindepth 2 -type f -name vars )
    echo $( expr $P + 1 )
}

gen_user() {
    local NAME="$1" LIBV=$LIBVV/$NAME

if grep -qs "^$NAME:" "$R/etc/passwd" ; then
    $Q echo Updating user $NAME
else
    $Q echo Generating user $NAME
    chr /sbin/adduser --disabled-login --home "$LIBV" --ingroup venus --system --comment "Venus Main User" $NAME
fi

grep -qs "^$NAME:" "$R/etc/passwd" || chr /sbin/adduser --disabled-login --home "$LIBV" --ingroup venus --system --comment "Venus Main User" $NAME

chr /sbin/adduser $NAME systemd-journal 2>/dev/null
chr /sbin/adduser $NAME dialout 2>/dev/null
chr /sbin/adduser $NAME bluetooth 2>/dev/null
test ! -v FB || chr /sbin/adduser $NAME video 2>/dev/null

SC="$LIBV/.config/systemd/user.control"
mkdir -p "$R/$SC/default.target.wants/"
fln "$SERVICE" "$R/$LIBV/.config/systemd/user"
fln ".config/systemd/user.control" "$R/$LIBV/service"

fcat "$R/$LIBV/nginx-fwd.conf" <<_END_
# XXX TODO this is broken when using native networking
#
location /$NAME/ {
        proxy_pass http://192.168.42.$SCREEN:80/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "Upgrade";

        gzip on;
        gzip_proxied any;
        proxy_http_version 1.1;
}
_END_

fcat "$R/$LIBV/.config/systemd/user.conf" <<_END_
[Manager]
DefaultEnvironment="PATH=$USRV/bin:/bin:/sbin"
_END_

mkdir -p "$R$LIBV/"{.etc,apps,conf,db,etc,log,themes,var/lib/venus-www-sessions,venus}

echo venusian > "$R$LIBV/etc/machine"
echo venusian > "$R$LIBV/etc/image-type"

USERID=$(grep "^$NAME:" $R/etc/passwd | ( IFS=: read a b c d ; echo $c ) )
env USER=$NAME UID=$USERID $USRV/bin/get-unique-id > $R$LIBV/conf/unique-id
cp $R$LIBV/conf/unique-id $R$LIBV/venus/unique-id

chr chown -R $NAME $LIBV/{.config,.etc,apps,conf,etc,db,var,log,venus}

VPW="$R$LIBV/conf/vncpassword.txt"
if test ! -s "$VPW" ; then
    read -s -p "VNC password: " pwd </dev/tty >/dev/tty 2>&1
    echo "$pwd" | "$HERE/lib/bin/gen-pw" >"$VPW"
    pwd=
elif [ $(stat -c '%s' "$VPW") -lt 50 ] ; then  # migrate
    "$HERE/lib/bin/gen-pw" < "$VPW" >"$VPW.n"
    mv "$VPW.n" "$VPW"
fi

mkdir -p "$R/$EV"

## Networking.

# Step 1: a bridged network interface for Venusian.

fcat "$R/etc/systemd/system/venusian-net.service" <<_END_
[Unit]
Description=Optional bridge interface for Venusian

[Service]
Type=oneshot
RemainAfterExit=yes

EnvironmentFile=-/etc/venusian/vars

ExecStart=/usr/lib/venusian/bin/setup-netif
ExecStop=true
# we don't actually take the interface down
# (a) Avahi gets confused when we reload
# (b) we attach the system's FlashMQ to the interface's IP address
_END_

# Step 1a: tell systemd-networkd to ignore new bridged nodes
#
fcat "$R/etc/systemd/network/00-venusian-any.network" <<_END_
[Match]
Name=venusian-*

[Network]
Description=An individual Venusian network link
Unmanaged=yes
RequiredForOnline=no
_END_

# Step 1bc: tell systemd-networkd to handle the bridge
#
fcat "$R/etc/systemd/network/00-venusian-br.netdev" <<_END_
[NetDev]
Name=venusian
Kind=bridge

[Bridge]
STP=no
_END_

fcat "$R/etc/systemd/network/00-venusian.network" <<_END_
[Match]
Name=venusian

[Network]
Description=Venusian network bridge
#Unmanaged=yes
ConfigureWithoutCarrier=yes
RequiredForOnline=no

DHCPServer=no

LinkLocalAddressing=no
LLMNR=no
LLDP=no
EmitLLDP=no

Address=192.168.42.254/24

#[DHCPServer]
#PoolOffset=130
#PoolSize=120
_END_

# Step 2: create a per-user network namespace
fcat "$R/etc/systemd/system/venusian-netns@.service" <<_END_
[Unit]
Description=Network namespace for Venusian %i
StopWhenUnneeded=true
Requires=venusian-net.service
After=venusian-net.service

[Service]
Type=oneshot
RemainAfterExit=yes
#PrivateNetwork=yes

EnvironmentFile=-/etc/venusian/vars
EnvironmentFile=-$EV/vars

# Ask ip netns to create a named network namespace
# (This ensures that things like /run/netns are properly setup)
ExecStart=/usr/lib/venusian/bin/setup-netspace %i

# Clean up
ExecStop=ip netns delete venusian-%i
_END_

# Step 2a: make the initial network namespace available
fcat "$R/etc/systemd/system/venusian-initns@.service" <<_END_
[Unit]
Description=Init namespace for Venusian %i
StopWhenUnneeded=true

[Service]
Type=oneshot
RemainAfterExit=yes

EnvironmentFile=-/etc/venusian/vars
EnvironmentFile=-$EV/vars

# Ask ip netns to create a named network namespace
# (This ensures that things like /run/netns are properly setup)
ExecStart=/usr/lib/venusian/bin/start-net %i

# Clean up
ExecStop=/usr/lib/venusian/bin/stop-net %i
_END_

# Step 3: Run the user.
#
fcat "$R/etc/systemd/system/venusian@.service" <<_END_
[Unit]
Description=Venusian Manager for UID %i
BindsTo=user-runtime-dir@%i.service
After=systemd-logind.service user-runtime-dir@%i.service dbus.service systemd-oomd.service

After=venusian-netns@%i.service venusian-initns@%i.service
Requires=venusian-netns@%i.service venusian-initns@%i.service

After=opt-victronenergy.mount $MNT_U
Requires=opt-victronenergy.mount $MNT_U

[Service]
User=%i
PAMName=systemd-user
Type=notify-reload
PrivateMounts=yes
ExecStart=/usr/lib/venusian/bin/run-user %i
Slice=user-%i.slice
# Reexecute the manager on service reload, instead of reloading.
# This provides a synchronous method for restarting all user manager
# instances after upgrade.
ReloadSignal=RTMIN+25
KillMode=mixed
Delegate=pids memory cpu
DelegateSubgroup=init.scope
TasksMax=infinity
TimeoutStopSec=120s
KeyringMode=inherit
OOMScoreAdjust=100
MemoryPressureWatch=skip

NetworkNamespacePath=/run/netns/venusian-%i
AmbientCapabilities=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN
AmbientCapabilities=CAP_NET_RAW
AmbientCapabilities=CAP_SYS_ADMIN  # sigh
AmbientCapabilities=CAP_CHOWN  # more sigh

BindPaths=/var/lib/venusian/%i:/data
#BindPaths=/var/lib/venusian/%i/etc:/etc/venus  # overlay, ExecStartPre
TemporaryFileSystem=/run/www

EnvironmentFile=-/etc/venusian/vars
EnvironmentFile=-$EV/vars
#Environment=XDG_RUNTIME_DIR=/run/venusian/%i

ExecStartPre=+mkdir -p /run/venusian/%i
ExecStartPre=+chown %i /run/venusian/%i
#ExecStartPost=+$USRV/bin/iptables-redirect on
#ExecStopPost=+$USRV/bin/iptables-redirect off
_END_

# Venus service (shortcut)
fcat "$R/etc/systemd/system/venus.target" <<_END_
[Unit]
Requires=venusian@venus.service

[Install]
RequiredBy=multi-user.target
_END_

if [ ! -s "$R/$EV/vars" ] || ! grep -qs "^SCREEN=" "$R/$EV/vars" ; then
    echo SCREEN=$SCREEN >>"$R/$EV/vars"
fi
if [ -v FB ] ; then
    echo FB=y >>"$R/$EV/vars"
fi
if [ -v EXT ] ; then
    echo "EXT='$ext'" >>"$R/$EV/vars"
fi

subs user
} # END gen_user


# command line processing
TEMP=$(getopt -o 'fFi:Id:hm:nqr:Rs:u:v?' --long 'dest:,ext:,fast,fb,force,help,image:,install,mount:,no-update,replace,repo:,repo-key:,root:,skip,sub:,user:,verbose' -n "$0" -- "$@")
if [ $? -ne 0 ]; then
    usage >&2
fi

set -e
eval set -- "$TEMP"
unset TEMP

Q=
verb=
root=/
FORCE=y
SUB=()
SUB_UPD=y
REPO=http://build.smurf.noris.de/info/smurf.list
REPOKEY=http://build.smurf.noris.de/info/smurf.archive.gpg
replace=
unset NAME DEST MNT img fast FB INST EXT

while : ; do
    case "$1" in
        (-h|-\?|--help)
            usage;
            exit 0 ;;
        (-q|--quiet)
            Q=":"
            shift ;;
        (--ext)
            EXT="$2"
            shift 2;;
        (-f|--force)
            FORCE=y
            shift ;;
        (-F|--fast)
            fast=y
            shift ;;
        (--fb)
            FB=y
            shift ;;
        (--skip)
            FORCE=""
            shift ;;
        (-n|--no-update)
            SUB_UPD=
            shift ;;
        (-v|--verbose)
            verb=y
            shift ;;
        (-R|--replace)
            replace=y
            shift ;;
        (-u|--user)
            NAME="$2"
            shift 2 ;;
        (-I|--inst|--install)
            INST=y
            shift ;;
        (-d|--dest)
            DEST="$2"
            shift 2 ;;
        (-i|--img|--image)
            img="$2"
            shift 2 ;;
        (-r|--root)
            root="$2"
            shift 2 ;;
        (-m|--mount)
            MNT="$2"
            shift 2 ;;
        (--repo)
            REPO="$2"
            shift 2 ;;
        (--repo-key)
            REPOKEY="$2"
            shift 2 ;;
        (-s|--sub)
            if test -d "$HERE/install.d/$2" ; then
                SUB+=("$2")
            else
                echo "Unknown subpart ('$2'). Exiting." >&2
		exit 2
            fi
            shift 2 ;;
        (--)
            shift; break ;;
        (*)
            echo "Internal error! '$1'" >&2
            exit 1
    esac
done

if [ "$(id -u)" != 0 ] ; then
    echo "This script needs to run as root. Sorry." >&2
    exit 1
fi

if test -v img ; then
    TMPDIR=/var/tmp
else
    TMPDIR=/tmp
fi
export TMPDIR

temp=$(mktemp -d -p $TMPDIR)
trap 'rm -r $temp' 0 1 2 15
cd $temp
umask 022

R="$(realpath "$root")"

LIBVV=/var/lib/venusian
USRV=/usr/lib/venusian
SERVICE="$USRV/service/"

if [ -v DEST ] || [ ! -v NAME ] ; then
    INST=y
fi
if [ ! -v DEST ] ; then
    DEST="$R/opt/venus"
fi

if [ ! -v MNT ] ; then
    MNT="${DEST:-/}"
fi

# drop duplicate and trailing slashes from $MNT and $DEST.
MNT="$(realpath -m "$MNT")"
[ "$MNT" = "/" ] && MNT=

DEST="$(realpath -m "$DEST")"

if [ -v NAME ] ; then
    if [ ! -v DEST ] ; then
        if [ ! -s /etc/systemd/system/opt-victronenergy.mount ] ; then
            echo "Adding users requires an existing Venusian installation." >&2
            usage >&2
            exit 2
        fi
        gen_user $NAME
        exit 0
    fi
else
    NAME=venus
fi

SCREEN=$(next_screen $NAME)
MNT_U=$(systemd-escape -m "$MNT")

EV="/etc/venusian/$NAME"

if test "$verb" = "y" ; then
    Q=":"
    set -x
fi

if [ $# -gt 0 ] ; then
    echo "Superfluous arguments. Exiting." >&2
    exit 2
fi

if [ -d "$USRV" ]; then
    echo "Existing installation found ($USRV)." >&2
    echo -n "Stopping Venusian users: "
    if [ -d /etc/venusian ] ; then
        ls /etc/venusian | while read u ; do 
            systemctl stop user@$u >/dev/null 2>&1 || true  # old
            systemctl stop venusian@$u || true
            echo -n "$u "
        done
    fi
    echo "."
    systemctl stop venusian-net || true
    umount /opt/victronenergy || true
    umount $DEST || true
    rm -r "$USRV"
fi

if [ -v INST ] && [ -v img ]; then
    if [ -z "$replace" ] && [ -d "$DEST" ]; then
        echo "Existing image found ($DEST). Either add '--replace', or don't use '--image'." >&2
        exit 2
    fi
    btrfs subvol delete "$DEST" 2>/dev/null || rm -rf "$DEST"
    test -d "$USRV" && rm -rf "$USRV"
fi

################# install local requirements
I=""
which systemd-nspawn >/dev/null 2>&1 || I="$I systemd-container"
which rsync >/dev/null 2>&1 || I="$I rsync"
if test -n "$I" ; then
    $Q echo Locally installing $I
    apt install $I
fi

if test -n "$SUB_UPD" ; then
    (
        cd "$HERE"
        git submodule update --init --recursive
    )
fi

################# COPY

if test -v img ; then
case "$img" in
    (http:*|https:*) DL="$img" ;;
    (-web-) DL=http://updates.victronenergy.com/feeds/venus/release/images/raspberrypi4/venus-image-raspberrypi4.wic.gz ;;
    (-rc-) DL=http://updates.victronenergy.com/feeds/venus/candidate/images/raspberrypi4/venus-image-raspberrypi4.wic.gz ;;
    # (-web*-) DL=?? ;;  # TODO get the link from somewhere
esac
fi

if test -v DL ; then
    F="$temp/img"
    if [ "${DL#.gz}" = "$DL" ] ; then
        wget -O - "$DL" | gzip -d > "$F"
    else
        wget -O $F "$DL"
    fi
    img="$F"
fi

if [ ! -v img ] ; then
    if [ ! -s "$DEST/etc/issue" ] ; then
        echo "No image given and no existing installation in '$DEST'. Terminating." >&2
        exit 1
    fi
    $Q echo "No image given; not copying."
else
$Q echo Copying image

if test -d "$DEST" ; then
   :
else
   btrfs subvol cre "$DEST" 2>/dev/null || mkdir "$DEST"
fi

# if the image is compressed, unpack it
imgz="$img"
img="${imgz%.gz}"
if [ "$img" != "$imgz" ] ; then
   img="$temp/${img##*/}"
   gzip -d < "$imgz" > "$img"
fi

mkdir $temp/dir
ld=$(losetup -f --show -P "$img")
trap 'losetup -d $ld; rm -r $temp' 0 1 2 15

mount ${ld}p2 $temp/dir
trap 'umount $temp/dir; losetup -d $ld; rm -r $temp' 0 1 2 15

if ! rsync -aX --numeric-ids --delete --inplace "$temp/dir/." "$DEST/." ; then
    echo "Sync from '$temp/dir/.' to '$DEST/.' failed. Exiting." >&2
    exit 1
fi
echo "Copy/sync finished."

umount $temp/dir; losetup -d $ld
trap 'rm -r $temp' 0 1 2 15
fi
################# END COPY


################# SETUP

if ! VERS=$(sed -ne 's/.* \(v[0-9]\.[0-9][0-9]*\).*/\1/p' <"$DEST/etc/issue") ; then
    echo Could not detect the Venus version in "'$DEST/etc/issue'" >&2
    exit 1
fi
if test -f "$root" ; then
    echo TODO root as an Image >&2
    exit 1
fi

DEST="$(realpath "$DEST")"

mkdir -p "$R/opt/victronenergy"
mkdir -p "$R/etc/venus"
mkdir -p "$R/data"
mkdir -p "$R/$USRV"/{opt,.opt}

chr() {
    if [ -n "$R" ] ; then
        chroot "$R" "$@"
    else
        "$@"
    fi
}

# create user
$Q echo Primary set-up
grep -qs "^venus:" "$R/etc/group" || chr /sbin/addgroup --system venus
grep -qs "^venusian:" "$R/etc/passwd" || chr /sbin/adduser --disabled-login --home "$LIBVV" --ingroup $NAME --system --comment "Venusian System" venusian

chr chgrp venus "$R/etc/venus"
chr chmod 775 "$R/etc/venus"
subs pre
# systemd
mkdir -p "$SERVICE"

## set up DBUS permissions
#for f in "$DEST/etc/dbus-1/system.d"/* ; do
#    g="$R/etc/dbus-1/system.d/${f##*/}"
#    test -s "$g" || \
#    sed <"$f" >"$g"  -e 's/"root"/"venus"/'
#done

cp -r "$HERE/lib/"* "$R$USRV/"

if [ "X$REPO" != "X-" ] ; then
    $Q echo "Adding repository (some packages are not yet in Debian)"

    test -s "$R/etc/apt/trusted.gpg.d/venusian.archive.gpg" || wget -q -O "$R/etc/apt/trusted.gpg.d/venusian.archive.gpg" $REPOKEY
    test -s "$R/etc/apt/sources.list.d/smurf.list" || \
    test -s "$R/etc/apt/sources.list.d/venusian.list" || wget -q -O "$R/etc/apt/sources.list.d/venusian.list" $REPO
fi

if ! test -v fast ; then
    if test "$R" = "/" ; then
        apt update
    else
        systemd-nspawn -D "$R" apt update
    fi
fi

$Q echo Checking startup scripts

lsrc() {
    ls "$DEST/etc/rcS.d"
    ls "$DEST/etc/rc5.d"
}

packages

# not using the obvious (ls;ls)| pipe here because of a bash bug:
# line numbers on errors below this point would be wrong
lsrc | while read f ; do
    f="${f%.sh}"
    case "$f" in
        ### Startup scripts, rcS.d
        (S01keymap) ;; # host OS
        (S02sysfs) ;; # mounts a bunch of directories; host OS
        (S02zzz-resize-sdcard) ;; # host OS
        (S03mountall) ;; # host OS
        (S03overlays) ;; # done later
        (S03test-data-partition) ;; # host problem
        (S04udev) ;; # host
        (S05checkroot) ;; # host
        (S0?modutils) ;; # host
        (S06alignment) ;; # host; mode 3 for alignment fixes (repair+complain)
        (S06checkroot) ;; # host
        (S06devpts) ;; # host
        (S07bootlogd) ;; # journal
        (S10overlays) ;; # done later
        (S20static-nodes) ;; # systemd
        (S29read-only-rootfs-hook) ;; # volatile /var/lib
        (S30clean-data) ;; # drop large log file
        (S36bootmisc) ;; # various system stuff
        (S37populate-volatile)
            # systemd
            # TODO set up /data
            ;;
        (S38dmesg) ;; # journald
        (S38urandom) ;; # random seed. Host.
        (S39hostname) ;; # host
        (S40read-eeprom) ;; # we don't have that
        (S50iptables) ;; # host
        (S80watchdog) ;; # possible TODO
        (S90gpio_pins) ;; # empty list
        (S90machine-conf) ;; # not on RPi
        (S99custom-rc-early)
            # TODO run /data/rcS.local
            ;;

### Startup scripts, rc5.d
        (S01networking) ;; # systemd-networkd or whatever
        (S02dbus-1) ;; # in base system
        (S09haveged) ;; # obsolete since kernel 5.6
        (S15mountnfs) ;; # system
        (S20apmd) ;; # not applicable on Raspberry Pi
        (S20bluetooth) ;; # host system
        (S20dnsmasq) ;; # host system
        (S20syslog) ;; # host system
        (S21avahi-daemon)
            ## host system, but ...
            mkdir -p "$R/etc/avahi"
            if test ! -f "$R/etc/avahi/avahi-daemon.conf" ; then
                $Q echo Installing avahi-daemon
                apti "$R" avahi-daemon
            fi
            sed -i -e s/^use-iff-running=/use-iff-running=yes/ "$R/etc/avahi/avahi-daemon.conf"

            ## TODO Garmin service file?
            ;;

        (S30update-data) ;; # TODO automatic data update
        (S60php-fpm) ;; # possibly some TODO or other
        (S70connman) ;; # host problem
        (S70swupdate) ;; # empty
        (S75avahi-autoipd) ;; # host problem
        (S80resolv-watch) ;; # systemd-resolved or some other host program
        (S82report-data-failure) ;; # local file system monitoring is not a Venus problem
        (S90crond)
            ## host OS
            # one builtin cron script, which does automated software updates,
            # which we don't do
            ;;

        (S95svscanboot)
            # SVC
            # TODO convert to systemd?
            ;;
        (S98scan-versions) ;; # alternate root file systems
        (S99check-updates) ;; # system update check
        (S99custom-rc-late)
            # TODO run /data/rc.local
            ;;
        (S99rmnologin) ;; # systemd
        (S99stop-bootlogd) ;; # journald

        (*)
            cat <<_ >/dev/stderr
UNKNOWN: startup script: $f

Please read the "Errors" section of our README.
_
            exit 1 ;;
    esac
done

################# random directories and links
$Q echo Checking symlinks
fln "$MNT/lib" "$R/l"
fln "lib" "$DEST/usr/l"
# fln "$MNT/opt/victronenergy" "$R/opt/victronenergy"
test -e "$R/opt/victronenergy" || mkdir -p "$R/opt/victronenergy"
fln "$MNT/usr/lib/fonts" "$R/usr/lib/fonts"
fln "$MNT/usr/lib/gconv" "$R/usr/lib/gconv"

fln "$MNT/var/www/venus" "$R/var/www/venus"

# if /o/v is a mountpoint, assume that it's our overlay,
# thus we write to that. Otherwise we write to the overlay's
# top directory.
if mountpoint -q "$R/opt/victronenergy" ; then
    if ! [ -d "$R/opt/victronenergy/gui" ] ; then
        echo "'$R/opt/victronenergy' is mounted but empty. Unmounting." >&2
        umount "$R/opt/victronenergy"
        OPTVIC="$R/$USRV/opt"
    else
        OPTVIC="$R/opt/victronenergy"
    fi
else
    OPTVIC="$R/$USRV/opt"
fi

################# Services

fchg "$HERE/udev.yml" "$R/$USRV/udev.yml" || \
    cp "$HERE/udev.yml" "$R/$USRV/udev.yml"
test -s "$R/$LIBVV/udev.yml" ||
    cp "$HERE/udev.example.yml" "$R/$LIBVV/udev.yml"
for f in $(ls "$HERE/service/") ; do
    fchg "$HERE/service/$f" "$R/$USRV/service/$f" || \
    sed -e "s#@USRV@#$USRV#g" -e "s#@LIBVV@#$LIBVV#g" \
        < "$HERE/service/$f" > "$R/$USRV/service/$f"
done

WANTS="$SERVICE/default.target.wants"
$Q echo Converting services
mkdir -p "$WANTS"
starters() {
    ls -1 "$DEST/opt/victronenergy/service/"
    echo "flashmq"
    echo "phpfpm"
}
starters | while read f ; do
    fx="${f##*/}"
    g="$SERVICE/$fx.service"
    test -n "$FORCE" || test ! -f "$g" || continue
    U=$temp/unit
    cat <<_END_ >$U
[Service]
_END_

    case "$fx" in
        (ppp) continue ;; # Of course not.
        (llmnrd) continue ;; # Not that either.
        (simple-upnpd) continue ;; # no
        (netmon) continue ;; # avahi restart on network change
        (nginx)
            # TODO investigate using the global nginx server directly
            echo >>$U ExecStartPre=$USRV/bin/gen-nginx-conf
            echo >>$U ExecStart=nginx -c /run/user/%U/nginx.conf
            echo >>$U ExecReload=nginx -c /run/user/%U/nginx.conf -s reload
            echo >>$U TimeoutStopSec=5
            echo >>$U KillMode=mixed
            echo >>$U AmbientCapabilities=CAP_NET_BIND_SERVICE
            ;;
        (serial-starter) # that's the job of our udev-handler
            fln "$SERVICE/udev-handler.service" "$WANTS/udev-handler.service"
            continue ;;
        (dbus-digitalinputs) continue ;; # TODO?
        (dbus-qwacs) continue ;; # ?
        (dbus-fronius) continue ;; # ?
        (dbus-adc) continue ;; # ?
        (dbus-ble-sensors)
            echo >>$U AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_ADMIN CAP_NET_RAW CAP_SYS_ADMIN
            echo >>$U ExecStart=nsenter --net=/run/venusian/%u/initns /opt/victronenergy/dbus-ble-sensors/dbus-ble-sensors
            ;;
        (venus-html5-logger) continue ;; # what for?
        (venus-access) continue ;; # TODO needs replacement
        # (venus-platform) continue ;; # TODO needs replacement
        (dbus-mqtt) continue ;; # superseded by dbus-flashmq
        (flashmq)
            echo >>$U LimitNOFILE=65536
            echo >>$U ExecStartPre=$USRV/bin/gen-flashmq-conf
            echo >>$U ExecStart=/usr/bin/flashmq --config-file /run/user/%U/flashmq.conf
            echo >>$U ExecReload=/bin/kill -HUP \$MAINPID
            ;;
        (gui)
            echo >>$U WorkingDirectory="/opt/victronenergy/gui"
            echo >>$U ExecStart="$USRV/bin/start-gui"
            echo >>$U AmbientCapabilities=CAP_NET_BIND_SERVICE
            ;;
        (ssh-tunnel) continue ;; # no remote access via some tunnel
        (vrmlogger) continue ;; # no external logging
        (phpfpm)
            V=$( dpkg -s php-fpm | sed -ne s/Version:\ *//p | sed -e s/.*:// -e s/+.*// )
            if test -z "$V" ; then
                echo Unable to determine php-fpm version >&2
                exit 1
            fi
            echo >>$U ExecStartPre=$USRV/bin/gen-phpfpm-conf
            echo >>$U ExecStart=php-fpm$V -y /run/user/%U/phpfpm.conf
            ;;
        (*)
            mkdir -p "$OPTVIC/service/$fx"
            (
                cat <<_
#!/bin/bash
BASH_ARGV0="$fx"

_
                sed -e '/^#!.bin.sh/d' -e /etc.profile.d/d -e '/^exec 2>&1$/d' <$MNT/opt/victronenergy/service/$fx/run
            ) | fcat "$OPTVIC/service/$fx/run"
            echo >>$U ExecStart=/opt/victronenergy/service/$fx/run "%N"
            ;;
    esac
    echo >>$U "Type=simple"
    echo >>$U "Restart=always"
    echo >>$U "RestartSec=10"
    echo >>$U "EnvironmentFile=-/etc/venusian/vars"
    echo >>$U "EnvironmentFile=-/etc/venusian/%u/vars"
    echo >>$U "EnvironmentFile=-/etc/venusian/%u/%N"
    echo >>$U "EnvironmentFile=-/run/user/%U/vars"
    echo >>$U "EnvironmentFile=-/run/user/%U/%N"
    if [ "$fx" != "localsettings" ] ; then
        echo >>$U ""
        echo >>$U "[Unit]"
        echo >>$U "Requires=localsettings.service"
        echo >>$U "After=localsettings.service"
    fi
    if [ "$fx" == "flashmq" ] ; then
        echo >>$U "Description=Per-User FlashMQ MQTT server"
        echo >>$U ""
        echo >>$U "[Install]"
        echo >>$U "WantedBy=multi-user.target"
    fi
    if [ "$fx" == "nginx" ] ; then
        echo >>$U "Description=Per-User NGINX server"
        echo >>$U "After=phpfpm.service"
        echo >>$U ""
        echo >>$U "[Install]"
        echo >>$U "WantedBy=multi-user.target"
    fi
    fcat "$SERVICE/$fx.service" <$U
    fln "$SERVICE/$fx.service" "$WANTS/$fx.service"

    rm $U
done

# fcat "$SERVICE/etc-venus.mount" <<_END_
# [Unit]
#
# [Mount]
# Where=/etc/venus
# What=/var/lib/venusian/%u/etc
# Type=fuse.fuse-overlayfs
# Options=allow_other,lowerdir=$DEST/etc/venus,upperdir=/var/lib/venusian/%u/etc,workdir=/var/lib/venusian/%u/.etc
# _END_

################# ELF starter

LA="$DEST/lib/ld-2.31.so"
if [ ! -s "$LA" ] ; then
    LA="$DEST/lib/ld-linux-armhf.so.3"
fi
if [ ! -s "$LA" ] ; then
    echo "No ARMHF loader found ($LA). Exiting." >&2
    exit 1
fi

LB="$R/lib/ld-linux-armhf.so.3"
L=
for S in "${SUB[@]}" ; do
    test -s "$S/lib" || continue
    L=y
    source "$S/lib"
done

if test -n "$L" ; then
    $Q echo Skip patching ld-linux-armhf
elif test ! -s "$LB" || test "$LA" -nt "$LB" ; then
    # HACK: Patch armhf loader to find venus libraries.
    # For binary alignment, ensure paths remain of same length!
    $Q echo Patching ld-linux-armhf
    sed -e 's#/lib/#/v/l/#' -e 's#/usr/lib/#/v/u/lib/#' < "$LA" > "$LB.n"
    if test $(stat --format %s "$LA") -ne $(stat --format %s "$LB.n") ; then
        echo Patching $LA to $LB did not work
        exit 1
    fi
    mv "$LB.n" "$LB"
    touch -r "$LA" "$LB"
    chmod 755 "$LB"
fi

################# Networking

fcat "$R/etc/sysctl.d/10-venusian.conf" <<_END_
net.ipv4.ip_forward=1
net.ipv4.conf.all.route_localnet=1
net.ipv4.conf.default.route_localnet=1
_END_

mkdir -p $R/etc/nginx/sites-available
mkdir -p $R/var/lib/venusian/web

if ! test -s "$R/etc/nginx/sites-available/venusian.conf" ; then
fcat "$R/etc/nginx/sites-available/venusian.conf" <<_END_
#
# This is an example configuration for your local nginx server.
# It is not auto-updated when you reinstall Venusian.

server {
    listen       80;
    listen       [::]:80;
    server_name  venusian.local;

    root         /var/lib/venusian/web;
    index        index.html ;

    location /.well-known/ {
        proxy_pass http://localhost/.well-known/;
        allow all;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }

    include /var/lib/venusian/*/nginx-fwd.conf;
}
_END_
fi

################# more random directories and links

mkdir -p "$R/v"
chmod 755 "$R/v"
fln "$MNT/lib" "$R/v/l"
fln "$MNT/usr" "$R/v/u"

mkdir -p "$OPTVIC/gui"
chmod 755 "$OPTVIC/gui"

NTW="$R/etc/systemd/system/network-online.target.wants"
mkdir -p "$NTW"
rm -f "$NTW/user@venus.service"  # old installation
fln /etc/systemd/system/venusian@.service "$NTW/venusian@venus.service"
fln /etc/systemd/system/venus.service "$R/etc/systemd/system/network-online.target.wants/venus.service"

mkdir -p "$OPTVIC/gui/qt-components/qml"
fln "$MNT/usr/lib/qtopia/plugins/gfxdrivers" "$OPTVIC/gui/gfxdrivers"
fln "$MNT/usr/lib/qml/QtQml" "$OPTVIC/gui/qt-components/qml/QtQml"

fln "$USRV/bin/get-unique-id" "$R/sbin/get-unique-id"
fln "$MNT/usr/bin/dbus" "$R/usr/bin/dbus"

################# overlay

# TODO check if the target system has a kernel-side overlayfs

fcat "$R/etc/systemd/system/opt-victronenergy.mount" <<_END_
[Unit]
After=sysinit.target
Requires=sysinit.target

[Mount]
Where=/opt/victronenergy
What=$USRV/opt
Type=fuse.fuse-overlayfs
Options=allow_other,lowerdir=$MNT/opt/victronenergy,upperdir=$USRV/opt,workdir=$USRV/.opt
_END_

################# patches

# Patch filters are located in $HERE/patch and $HERE.install.d/NAME/patch.
# Their relative path is appended to /opt/victronenergy: that file is patched.

vfind() { # file
    local p="$1"
    if [ ! -d "$p.V" ] ; then echo $p; return 0; fi
    while read v ; do
        if ! [ $v \< $VERS ] ; then
            echo $p.V/$v; return 0
        fi
    done < <(ls "$p.V" | sort)
    echo $p; return 0
}

pat() { # path [sub]
    local p="$1"
    local f="$(realpath --relative-to "$2" "$1")"
    local fs="$DEST/opt/victronenergy/$f"
    local fd="$OPTVIC/$f"
    if ! test -s "$fs" ; then return; fi
    p="$(vfind $p)"
    fchg "$fs" "$fd" || \
        if test -x $p ; then
            $p < $fs > $fd
        else
            ft="$temp/$(basename "$fd")"
            cp "$fs" "$ft"
            if ! patch $ft < $p ; then
                echo "Patch '$p' (to file '$fs') did not apply." >&2
                echo "Please create a versioned patch (see docs) and try again." >&2
                exit 1
            fi
            cp "$ft" "$fd"
        fi
}

find "$HERE/patch" -type f | while read f ; do
    pat "$f" "$HERE/patch"
done
for S in "${SUB[@]}" ; do
    D="$HERE/install.d/$S/patch"
    test -d "$D" || continue
    find "$D" -type f | while read f ; do
        pat "$f" "$D"
    done
done

cd
mkdir -p "$OPTVIC/dbus-modbus-client"
for f in $(ls "$HERE/ext/dbus-modbus-client") ; do
    if ! cmp --silent "$HERE/ext/dbus-modbus-client/$f" "$OPTVIC/dbus-modbus-client/$f" ; then
        cp -a "$HERE/ext/dbus-modbus-client/$f" "$OPTVIC/dbus-modbus-client/$f"
    fi
done
if ! rsync -rEt --delete --inplace --cvs-exclude --exclude=meter-library "$HERE/ext/dbus-modbus-client" "$OPTVIC/" ; then
    echo "Sync from 'ext/dbus-modbus-client' to '$OPTVIC/' failed. Exiting." >&2
    exit 1
fi
if ! rsync -rEt --delete --inplace --cvs-exclude "$HERE/ext/meter-library" "$OPTVIC/dbus-modbus-client/" ; then
    echo "Sync from 'ext/meter-library' to '$OPTVIC/dbus-modbus-client/' failed. Exiting." >&2
    exit 1
fi

################# mountpoint

if [ "$(realpath "$MNT")" != "$(realpath "$DEST")" ] ; then
    mkdir -p "$R/$MNT"

    if [ "$R" = "/" ] ; then
        fcat "$R/etc/systemd/system/$MNT_U" <<_END_
[Unit]
After=sysinit.target
Requires=sysinit.target

[Mount]
Where=$MNT
What=$DEST
Type=none
Options=bind
_END_
    elif [ "$(realpath "$R/$MNT")" != "$(realpath "$DEST")" ] ; then
        echo "** You need to configure mounting $MNT manually **" >&2
    else
        MNT_U=
    fi
else
    MNT_U=
fi

################# finish

find "$R/$USRV" -type d -print0|xargs -0 chmod 755
find "$R/$USRV/"{bin,opt} -type f -print0|xargs -0 chmod 755

gen_user $NAME

subs post

if test "$R" = "/" ; then
	systemctl daemon-reload
	systemctl reload systemd-networkd || true  # may not be running
fi

$Q echo "Done."
